Article.create({"title"=>"Blog created!", "body"=>"We're living in a golden age.  All you need is gold.", "status"=>"public"})
Comment.create({"commenter"=>"Веселый банан", "body"=>"Йоу бро! Я рад что ты запустил свой блог!\n\n<h1 style=\"color: yellow; background-color: black;\">Это очень круто!</h1>", "article_id"=>1, "status"=>"public"})
Comment.create({"commenter"=>"Веселый банан ", "body"=>"Жаль правда форматирование в комментариях не работает ☹️\n\n<h1 style=\"background-color: yellow; color: black;\">Грущу</h1>", "article_id"=>1, "status"=>"public"})
Article.create({"title"=>"First post", "body"=>"It's really quite a simple choice: Life, Death, or Los Angeles.", "status"=>"public"})
Article.create({"title"=>"Second post", "body"=>"No one knows like a woman how to say things that are at once gentle and deep.", "status"=>"public"})
